### PR TITLE
Added note about Yarn requirement

### PR DESCRIPTION
**Pull request by lukors**
Ran into this while following the instructions and figured it wouldn't hurt to add a note about it to smooth things out for anyone following this.

### CODE REVIEW

**Comment by happybeing** [comment]
Thanks Lukas. I'm not sure about this as I don't use yarn, I use npm and all the instructions use that. Do you think we should switch everything to yarn? I think best one or the other, but I'm not sure as I've mainly used npm.

EDITED above because for some reason at first I thought this was safenetworkjs repo! I'm not awake yet!

**Comment by lukors** [comment]
When I ran `npm install` in the `safenetworkjs` directory I got an error after a while about how "yarn was not recognized as a command" or something like that. So I installed Yarn, and then it worked.

The reason for this pull request was that I ran into this issue, had to look at the error to figure out how it could be fixed, and try installing Yarn and running the command again to see if it worked. If I had been instructed that Yarn was required I could have saved some effort, and figured it would be useful if any future people following the instructions didn't have to do the same.

It's odd that you don't need it on your end. Could it be a Windows specific thing?

**Comment by happybeing** [comment]
Ah OK, I hadn't realised that sorry. My bad. I do have yarn installed, so it must be being used indirectly by something that npm installs. That seems odd, but yes, your PR makes sense then. Thanks again. I'm offline mostly for a while so may not merge it until next week as I might look into the cause a bit first.

**Comment by lukors** [comment]
No problem! Maybe I could've been clearer about the reason behind this PR.

Glad to help!

**Pull request merged**
